### PR TITLE
Make linefeed OS-agnostic in unit tests

### PR DESCRIPTION
**Pull request by Nilzor**
Ensure no tests fail due to \n differs to \r\n on Windows,
while maintaining Linux/MacOS compatibility

*edit*: Might hold off the merge until I've verified that tests in `HtmlReportSpec` passes. I'm struggling to generate `app.min.js` (or you can verify it on AppVeyor)

*edit 2*: `HtmlReportSpec` have other issues not related to Linefeed or Windows. I believe this PR can be merged

### CODE REVIEW

**Comment by Nilzor** [comment]
Appveyor result: https://ci.appveyor.com/project/Nilzor/composer/build/appveyor%204#L454

Down to 6 errors - all related to `HtmlReportSpec.kt`, which requires a lot more work to fix on Windows (Not linefeed-related)

**Comment by yunikkk** [comment]
@Nilzor regarding 6 issues with the `HtmlReportSpec.kt` - tests expect Nodejs is present and are supposed to work in Docker container with `ci/build.sh`, which contains all the needed environment for that. 
I guess we'll need a separate script and container for running all on Windows (or is running Linux Docker images possible/not painful on Windows, I'm not sure really).

**Comment by Nilzor** [comment]
Do we really _need_ to be able to run the tests on Windows though? Having the production code running on Windows and having the development environment run are two different things. 

Running docker on Windows is definitely possible, I'm just not sure it's worth investing in it. There are a couple of approaches we could take:
 - Create a Windows version of `build.sh` : `build.ps1` or `build.cmd`. 
 - Document how to run Docker in _Bash on Ubuntu for Windows_ and make any changes needed, if any (I haven't tried that approach yet - not sure if Docker will run in this environment)
 - Document how to run Docker in Linux VM on Windows (Basically not supporting Windows as a unit testing enviornment)

I'm leaning towards number 3, or not doing anything at all with regards to testing on Windows

**Comment by Nilzor** [comment]
PS: Thanks for the merge - could you also please make a new release build?

**Comment by yunikkk** [comment]
Well, running all tests on Windows would make us sure that all stuff continues working on Windows after new changes. 
Let's stick with option 3 for now, ideally considering 1 one somewhere in future)

**Comment by yunikkk** [comment]
Pushed new release, too.

**Pull request merged**
