### PR TITLE
Restructure list of options, add examples and defaults.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
I think that'll make it easier for people to understand what options are doing and how to customize them :)

### CODE REVIEW

**Comment by yunikkk** [comment]
Well, it actually can be called by humans from CLI, too. At least I'm using it sometimes and I strongly believe I am)
So sure I wrote some aliases to ease composer using. But it would be so muuuuuuuch easier to have the short args, too...

**Comment by artem-zinnatullin** [comment]
>At least I'm using it sometimes and I strongly believe I am)

Beginner's mistake :trollface:

**Comment by yunikkk** [comment]
My point is - let users decide on their own how to write arguments)

**Comment by artem-zinnatullin** [comment]
Yeah, but then coming up with single letter arg names is really hard and we'll start getting conflicts, I'm not opposed as long as we keep full names hehe

**Pull request merged**
