### PR TITLE
Refactor out exit calls

### PR DESCRIPTION
**Pull request by trevjonez**
This will allow me to run composer from within process of gradle via the worker api.

in support of https://github.com/gojuno/composer/issues/77

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Hm, wait, are you planning to include `Composer` as compile/runtime dependency of the plugin and invoke it as code rather than as separate process?

**Comment by trevjonez** [comment]
Correct, gradle has a new worker api that offers different levels of isolation so it will still run isolated but not as a `javaexec` or `exec`as it would have been done prior to gradle 4.0. Since it will be run in a worker daemon or potentially in the main gradle process I can't have system.exit calls terminating the entire run.

As I look at all the code in `main` part of me wonders if wouldn't be better to take a card from spoon   so that there is a builderish api to configure and the main.kt is just a wrapper around said classes to enable use from a CLI.

**Comment by artem-zinnatullin** [comment]
Well, we can do this, but current version of Composer is not designed to be
used as a library, we don't maintain API compatibility of Composer
internals since we've designed it for command line invocations.

Are they any good reasons to not invoke it as a separate process? Because
maintaining API compatibility for Composer Internals will definitely slow
down and complicate its development..

**Comment by trevjonez** [comment]
So as I play with this using java exec rather than the worker api it is much simpler to do. I wonder if a  tighter integration still wouldn't be a bad thing but as is this keeps it simple

Happy side effect of javaexec is that it gives me a chance to inject environment variables via the task config dsl making my test behave as expected.

Going to close this since javaexec just makes both projects stay more simple at the expense of 5s jvm start overhead. at some point a deeper integration might be nice but it boils down to opinions at that point.

**Comment by artem-zinnatullin** [comment]
>Happy side effect of javaexec is that it gives me a chance to inject environment variables

Yis!

>At some point a deeper integration might be nice but it boils down to opinions at that point.

Yup, let's see how this goes, on the other hand we will now pay more attention to internal APIs to make this transition easier in future, thanks for understanding!

**Pull request closed without merging**
